# 크롤링 방법
- 1단계 : 한개의 상품 크롤링
- 2단계 : 여러개의 상품 크롤링
- 3단계 : 여러페이지 크롤링
- 4단계 ; 데이터 엑셀에 저장
---

### 3단계 : 여러페이지 크롤링
> 수집할 정보 : 카테고리, 상품명, 상세페이지링크, 가격 <br/>
> URL 구조 : Protocol, DOmain, Path, Parameter(key=value)

#### 페이지를 바꾸면서 URL이 변경되는 부분 찾기
> https://startcoding.pythonanywhere.com/basic?page=1 <br/>
> https://startcoding.pythonanywhere.com/basic?page=2 <br/>
> https://startcoding.pythonanywhere.com/basic?page=3 <br/>
> ...........................  <br/>
> https://startcoding.pythonanywhere.com/basic?page=10 <br/>

In [1]:
for i in range(1, 5):
    print(i)

1
2
3
4

#### 문자열과 변수(데이터)를 합쳐서 새로운 문자열을 만들때 사용

In [3]:
name = "뽀로로"
age = 7

greeting = f"안녕하세요, 제이름은 {name}입니다. 나이는 {age}살입니다."
greeting

'안녕하세요, 제이름은 뽀로로입니다. 나이는 7살입니다.'

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [7]:
target_url_pages = "https://startcoding.pythonanywhere.com/basic?page={pg}"

for i in range(1, 5):
    target_url = target_url_pages.format(pg=i)
    print(target_url)
    # response = requests.get(target_url)
    # html = response.text
    # soup = BeautifulSoup(html, 'html.parser')
    # soup

https://startcoding.pythonanywhere.com/basic?page=1
https://startcoding.pythonanywhere.com/basic?page=2
https://startcoding.pythonanywhere.com/basic?page=3
https://startcoding.pythonanywhere.com/basic?page=4

In [10]:
target_url_pages = "https://startcoding.pythonanywhere.com/basic?page={pg}"

for i in range(1, 5):
    target_url = target_url_pages.format(pg=i)
    response = requests.get(target_url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    print(target_url)
    print("-" * 50)
    items = soup.select(".product")

    for item in items:
        p_category = item.select_one(".product-category").get_text()

        item_name  = item.select_one(".product-name")   
        p_name = item_name.get_text()
        p_link = item_name.select_one("a")["href"]

        p_price = item.select_one(".product-price").get_text()
        p_price = p_price.split("원")[0]
        p_price = p_price.replace(",", "")
        p_price = p_price.strip() 
        p_price = int( p_price )

        # print(f"카테고리 : {p_category}, 상품명 : {p_name}, 가격 : {p_price} 원, 상세페이지 : {p_link}")

https://startcoding.pythonanywhere.com/basic?page=1
--------------------------------------------------
https://startcoding.pythonanywhere.com/basic?page=2
--------------------------------------------------
https://startcoding.pythonanywhere.com/basic?page=3
--------------------------------------------------
https://startcoding.pythonanywhere.com/basic?page=4
--------------------------------------------------

In [12]:
target_url_pages = "https://startcoding.pythonanywhere.com/basic?page={pg}"

p_category_arr = []
p_name_arr = []
p_link_arr = []
p_price_arr = []

for i in range(1, 5):
    target_url = target_url_pages.format(pg=i)
    response = requests.get(target_url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    print(target_url)
    print("-" * 50)
    items = soup.select(".product")

    for item in items:
        p_category = item.select_one(".product-category").get_text()

        item_name  = item.select_one(".product-name")   
        p_name = item_name.get_text()
        p_link = item_name.select_one("a")["href"]

        p_price = item.select_one(".product-price").get_text()
        p_price = p_price.split("원")[0]
        p_price = p_price.replace(",", "")
        p_price = p_price.strip() 
        p_price = int( p_price )

        # print(f"카테고리 : {p_category}, 상품명 : {p_name}, 가격 : {p_price} 원, 상세페이지 : {p_link}")
        p_category_arr.append(p_category)
        p_name_arr.append(p_name)
        p_link_arr.append(p_link)
        p_price_arr.append(p_price)

https://startcoding.pythonanywhere.com/basic?page=1
--------------------------------------------------
https://startcoding.pythonanywhere.com/basic?page=2
--------------------------------------------------
https://startcoding.pythonanywhere.com/basic?page=3
--------------------------------------------------
https://startcoding.pythonanywhere.com/basic?page=4
--------------------------------------------------

In [14]:
len(p_category_arr), len(p_name_arr), len(p_link_arr), len(p_price_arr)

(35, 35, 35, 35)

In [23]:
data = { '카테고리':p_category_arr, '상품명':p_name_arr, '상세페이지':p_link_arr, '가격':p_price_arr }
df = pd.DataFrame(data) 
df.head(10)

,카테고리,상품명,상세페이지,가격
0,노트북,"에이서 스위프트 GO 16 OLED, 스틸 그레이, 코어i7, 512GB, 16GB...",#product1_detail.html,1419000
1,노트북,"삼성전자 노트북 플러스2 15.6, 퓨어 화이트, NT550XDA-K24AT, 펜티...",#product2_detail.html,549000
2,노트북,"레노버 아이디어패드 슬림 1 15AMN7 15.6, 256GB, Free DOS, ...",#product3_detail.html,529000
3,노트북,"레노버 V15 G4 AMN 15.6, Arctic Grey, 라이젠3, 256GB,...",#product4_detail.html,624000
4,노트북,"LG 울트라PC 엣지 16, 차콜 그레이, 라이젠5, 256GB, 16GB, WIN...",#product5_detail.html,1135000
5,노트북,"베이직스 베이직북 14 3세대, BB1422SS, 256GB, White, WIN1...",#product6_detail.html,398000
6,노트북,"레노버 아이디어패드 슬림 5i 14IRL 14, Cloud Grey, 코어i5, 5...",#product7_detail.html,899000
7,노트북,"레노버 아이디어패드 슬림 5 16IRL 16, Cloud Grey, 512GB, 1...",#product8_detail.html,929000
8,노트북,"에이서 스위프트 GO 16 OLED, 스틸 그레이, 코어i5, 512GB, 16GB...",#product9_detail.html,1008000
9,노트북,"삼성전자 갤럭시북 2 15.6, 500GB, 실버, NT550XED-K78AS, 코...",#product10_detail.html,1149000

In [24]:
df = pd.DataFrame(data, columns=[ '카테고리', '상품명', '가격', '상세페이지'])
df.tail(5)

,카테고리,상품명,가격,상세페이지
30,모니터,"주연테크 54.6cm FHD LED 모니터 100Hz, V22FX(일반)",89000,#product31_detail.html
31,모니터,"LG전자 60.4cm FHD 모니터, 24MQ400C",145000,#product32_detail.html
32,모니터,KOORUI 60.45cm FHD 게이밍 모니터 리얼 165Hz 1ms MPRT+프...,85900,#product33_detail.html
33,모니터,"LG전자 68.6cm FHD 모니터, 27MQ400C",169750,#product34_detail.html
34,모니터,KOORUI 60.45cm FHD Fast IPS 리얼 165Hz 1ms(gtg) ...,139000,#product35_detail.html

In [25]:
df.tail(5)

,카테고리,상품명,가격,상세페이지
30,모니터,"주연테크 54.6cm FHD LED 모니터 100Hz, V22FX(일반)",89000,#product31_detail.html
31,모니터,"LG전자 60.4cm FHD 모니터, 24MQ400C",145000,#product32_detail.html
32,모니터,KOORUI 60.45cm FHD 게이밍 모니터 리얼 165Hz 1ms MPRT+프...,85900,#product33_detail.html
33,모니터,"LG전자 68.6cm FHD 모니터, 27MQ400C",169750,#product34_detail.html
34,모니터,KOORUI 60.45cm FHD Fast IPS 리얼 165Hz 1ms(gtg) ...,139000,#product35_detail.html

In [26]:
df.to_csv('data/product_info.csv', sep=',', encoding='UTF-8')

In [32]:
%ls data

 C ����̺��� ����: ���� ��ũ
 ���� �Ϸ� ��ȣ: C2C3-D32B

 c:\GitHub\D2505_WebCrawling\02.����������ũ�Ѹ�\data ���͸�

2025-05-02  ���� 07:50    <DIR>          .
2025-05-02  ���� 07:50    <DIR>          ..
2025-05-02  ���� 07:50             4,973 product_info.csv
               1�� ����               4,973 ����Ʈ
               2�� ���͸�  796,293,599,232 ����Ʈ ����

In [34]:
data_df = pd.read_csv('data/product_info.csv', encoding='UTF-8')
data_df.head(5)

,Unnamed: 0,카테고리,상품명,가격,상세페이지
0,0,노트북,"에이서 스위프트 GO 16 OLED, 스틸 그레이, 코어i7, 512GB, 16GB...",1419000,#product1_detail.html
1,1,노트북,"삼성전자 노트북 플러스2 15.6, 퓨어 화이트, NT550XDA-K24AT, 펜티...",549000,#product2_detail.html
2,2,노트북,"레노버 아이디어패드 슬림 1 15AMN7 15.6, 256GB, Free DOS, ...",529000,#product3_detail.html
3,3,노트북,"레노버 V15 G4 AMN 15.6, Arctic Grey, 라이젠3, 256GB,...",624000,#product4_detail.html
4,4,노트북,"LG 울트라PC 엣지 16, 차콜 그레이, 라이젠5, 256GB, 16GB, WIN...",1135000,#product5_detail.html

In [35]:
# index_col='Unnamed: 0'') 삭제
del data_df['Unnamed: 0']
data_df.head()

,카테고리,상품명,가격,상세페이지
0,노트북,"에이서 스위프트 GO 16 OLED, 스틸 그레이, 코어i7, 512GB, 16GB...",1419000,#product1_detail.html
1,노트북,"삼성전자 노트북 플러스2 15.6, 퓨어 화이트, NT550XDA-K24AT, 펜티...",549000,#product2_detail.html
2,노트북,"레노버 아이디어패드 슬림 1 15AMN7 15.6, 256GB, Free DOS, ...",529000,#product3_detail.html
3,노트북,"레노버 V15 G4 AMN 15.6, Arctic Grey, 라이젠3, 256GB,...",624000,#product4_detail.html
4,노트북,"LG 울트라PC 엣지 16, 차콜 그레이, 라이젠5, 256GB, 16GB, WIN...",1135000,#product5_detail.html